cluster_name: 

argocd:
  version: 
  argo_url_prefix: 

externaldns:
  version: 
  dnsZones: []

certmanager:
  version: 
  replicaCount: 1

metricsServer:
  version: 

envoyGateway:
  version: 
  replicas: 1

externalGateway:
  name: external-gateway
  namespace: envoy-gateway-system

prometheus_crds:
  version: 
  
prometheus_stack:
  version: 
  prometheus_url: 
  alertmanager_url: 
  grafana_url: 
